Update 3-metadata-standards.md
elixir-europe-training/ELIXIR-TrP-FAIR-Converge pull request #146
Opened 2024-11-06 09:19 UTC by nrvanulzen

Primarily rewrote the overview part in the way we decided. I left original text as comments because it contains things that should somehow be incorporated into the table or lesson outline

2024-11-06 13:32 UTC, bianchini88 requested changes
Add yourself to the contributors as indicated in the review. 
Note that UK spelling is preferred for these pages.

2024-11-06 13:32 UTC, bianchini88 commented on docs/units/findable-data/topics/3-metadata-standards.md
> +  - "0000-0003-0771-3516"
Add contributor info to the contributors' table (https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-Converge/blob/main/_data/contributors.yaml) as part of this PR

2024-11-06 13:32 UTC, bianchini88 commented on docs/units/findable-data/topics/3-metadata-standards.md
> +Participants will understand the significance of rich metadata in the context of life sciences datasets, learn how to describe and search for datasets using metadata standards, and recognize the role
```suggestion
Participants will understand the significance of rich metadata in the context of life sciences datasets, learn how to describe and search for datasets using metadata standards, and recognise the role metadata standards play in dataset discovery. The focus is on FAIR principle F2, which is primarily about discovery from both a generic and a domain-specific perspective.
```

2024-11-07 09:05 UTC, konradana approved these changes

2024-11-07 09:06 UTC, bianchini88 approved these changes

2024-11-07 09:06 UTC, merged